/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Pre2RouteImport } from './routes/pre2'
import { Route as PastExamsRouteImport } from './routes/past-exams'
import { Route as R9RouteImport } from './routes/9'
import { Route as R8RouteImport } from './routes/8'
import { Route as R7RouteImport } from './routes/7'
import { Route as R6RouteImport } from './routes/6'
import { Route as R5RouteImport } from './routes/5'
import { Route as R4RouteImport } from './routes/4'
import { Route as R3RouteImport } from './routes/3'
import { Route as R2RouteImport } from './routes/2'
import { Route as R10RouteImport } from './routes/10'
import { Route as IndexRouteImport } from './routes/index'

const Pre2Route = Pre2RouteImport.update({
  id: '/pre2',
  path: '/pre2',
  getParentRoute: () => rootRouteImport,
} as any)
const PastExamsRoute = PastExamsRouteImport.update({
  id: '/past-exams',
  path: '/past-exams',
  getParentRoute: () => rootRouteImport,
} as any)
const R9Route = R9RouteImport.update({
  id: '/9',
  path: '/9',
  getParentRoute: () => rootRouteImport,
} as any)
const R8Route = R8RouteImport.update({
  id: '/8',
  path: '/8',
  getParentRoute: () => rootRouteImport,
} as any)
const R7Route = R7RouteImport.update({
  id: '/7',
  path: '/7',
  getParentRoute: () => rootRouteImport,
} as any)
const R6Route = R6RouteImport.update({
  id: '/6',
  path: '/6',
  getParentRoute: () => rootRouteImport,
} as any)
const R5Route = R5RouteImport.update({
  id: '/5',
  path: '/5',
  getParentRoute: () => rootRouteImport,
} as any)
const R4Route = R4RouteImport.update({
  id: '/4',
  path: '/4',
  getParentRoute: () => rootRouteImport,
} as any)
const R3Route = R3RouteImport.update({
  id: '/3',
  path: '/3',
  getParentRoute: () => rootRouteImport,
} as any)
const R2Route = R2RouteImport.update({
  id: '/2',
  path: '/2',
  getParentRoute: () => rootRouteImport,
} as any)
const R10Route = R10RouteImport.update({
  id: '/10',
  path: '/10',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/10': typeof R10Route
  '/2': typeof R2Route
  '/3': typeof R3Route
  '/4': typeof R4Route
  '/5': typeof R5Route
  '/6': typeof R6Route
  '/7': typeof R7Route
  '/8': typeof R8Route
  '/9': typeof R9Route
  '/past-exams': typeof PastExamsRoute
  '/pre2': typeof Pre2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/10': typeof R10Route
  '/2': typeof R2Route
  '/3': typeof R3Route
  '/4': typeof R4Route
  '/5': typeof R5Route
  '/6': typeof R6Route
  '/7': typeof R7Route
  '/8': typeof R8Route
  '/9': typeof R9Route
  '/past-exams': typeof PastExamsRoute
  '/pre2': typeof Pre2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/10': typeof R10Route
  '/2': typeof R2Route
  '/3': typeof R3Route
  '/4': typeof R4Route
  '/5': typeof R5Route
  '/6': typeof R6Route
  '/7': typeof R7Route
  '/8': typeof R8Route
  '/9': typeof R9Route
  '/past-exams': typeof PastExamsRoute
  '/pre2': typeof Pre2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/10'
    | '/2'
    | '/3'
    | '/4'
    | '/5'
    | '/6'
    | '/7'
    | '/8'
    | '/9'
    | '/past-exams'
    | '/pre2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/10'
    | '/2'
    | '/3'
    | '/4'
    | '/5'
    | '/6'
    | '/7'
    | '/8'
    | '/9'
    | '/past-exams'
    | '/pre2'
  id:
    | '__root__'
    | '/'
    | '/10'
    | '/2'
    | '/3'
    | '/4'
    | '/5'
    | '/6'
    | '/7'
    | '/8'
    | '/9'
    | '/past-exams'
    | '/pre2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R10Route: typeof R10Route
  R2Route: typeof R2Route
  R3Route: typeof R3Route
  R4Route: typeof R4Route
  R5Route: typeof R5Route
  R6Route: typeof R6Route
  R7Route: typeof R7Route
  R8Route: typeof R8Route
  R9Route: typeof R9Route
  PastExamsRoute: typeof PastExamsRoute
  Pre2Route: typeof Pre2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pre2': {
      id: '/pre2'
      path: '/pre2'
      fullPath: '/pre2'
      preLoaderRoute: typeof Pre2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-exams': {
      id: '/past-exams'
      path: '/past-exams'
      fullPath: '/past-exams'
      preLoaderRoute: typeof PastExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/9': {
      id: '/9'
      path: '/9'
      fullPath: '/9'
      preLoaderRoute: typeof R9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/8': {
      id: '/8'
      path: '/8'
      fullPath: '/8'
      preLoaderRoute: typeof R8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/7': {
      id: '/7'
      path: '/7'
      fullPath: '/7'
      preLoaderRoute: typeof R7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/6': {
      id: '/6'
      path: '/6'
      fullPath: '/6'
      preLoaderRoute: typeof R6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/5': {
      id: '/5'
      path: '/5'
      fullPath: '/5'
      preLoaderRoute: typeof R5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/4': {
      id: '/4'
      path: '/4'
      fullPath: '/4'
      preLoaderRoute: typeof R4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3': {
      id: '/3'
      path: '/3'
      fullPath: '/3'
      preLoaderRoute: typeof R3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2': {
      id: '/2'
      path: '/2'
      fullPath: '/2'
      preLoaderRoute: typeof R2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/10': {
      id: '/10'
      path: '/10'
      fullPath: '/10'
      preLoaderRoute: typeof R10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R10Route: R10Route,
  R2Route: R2Route,
  R3Route: R3Route,
  R4Route: R4Route,
  R5Route: R5Route,
  R6Route: R6Route,
  R7Route: R7Route,
  R8Route: R8Route,
  R9Route: R9Route,
  PastExamsRoute: PastExamsRoute,
  Pre2Route: Pre2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
